replicaCount: 1

image:
  repository: python
  tag: "3.10.5-alpine3.16"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
